# stubs/tiktoken/__init__.pyi

class Encoding:
    def encode(self, text: str) -> list[int]: ...
    def decode(self, tokens: list[int]) -> str: ...

def encoding_for_model(model_name: str) -> Encoding: ...
def get_encoding(name: str) -> Encoding: ...

__version__: str
